image: edbizarro/gitlab-ci-pipeline-php:8.0-alpine

stages:
  - build
  - test
  - security

composer:
  stage: build
  script:
    - sudo composer self-update --2
    - mkdir -p storage/framework/{sessions,views,cache}
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts --no-plugins --ignore-platform-reqs
  artifacts:
    expire_in: 30 days
    paths:
      - vendor/
      - .env

phpunit:
  stage: test
  script:
    - sudo composer self-update --2
    - mkdir -p storage/framework/{sessions,views,cache}
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts --ignore-platform-reqs
    - artisan test --parallel

sensiolabs:
  stage: security
  script:
    - curl -L -sS --output local-php-security-checker https://github.com/fabpot/local-php-security-checker/releases/download/v1.2.0/local-php-security-checker_1.2.0_linux_amd64
    - chmod +x ./local-php-security-checker
    - ./local-php-security-checker --no-dev
  dependencies: []
  cache:
    paths:
      - ../composer.json


